#!/bin/sh

echo python3 scaling_behavior.py "$@"

srun -K \
    --partition=A100-SDS,A100-RP,A100-80GB,A100-40GB \
    --gpus-per-task=1 \
    --gpu-bind=none \
    --container-image=/netscratch/nauen/images/custom_ViT_v10.sqsh \
    --container-workdir="`pwd`" \
    --container-mounts=/netscratch/$USER:/netscratch/$USER,/ds-sds:/ds-sds:ro,"`pwd`":"`pwd`" \
    --job-name="Taylor-Attention Scaling Behavior" \
    --ntasks=1 \
    --cpus-per-task=4 \
    --mem=32G \
    --time=20:00:00 \
python3 scaling_behavior.py "$@"
